# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nishanth/Documents/ai-git-agent

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nishanth/Documents/ai-git-agent/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nishanth/Documents/ai-git-agent/build/CMakeFiles /home/nishanth/Documents/ai-git-agent/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nishanth/Documents/ai-git-agent/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AIGitAgent

# Build rule for target.
AIGitAgent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AIGitAgent
.PHONY : AIGitAgent

# fast build rule for target.
AIGitAgent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/build
.PHONY : AIGitAgent/fast

src/GitHandler.o: src/GitHandler.cpp.o
.PHONY : src/GitHandler.o

# target to build an object file
src/GitHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/GitHandler.cpp.o
.PHONY : src/GitHandler.cpp.o

src/GitHandler.i: src/GitHandler.cpp.i
.PHONY : src/GitHandler.i

# target to preprocess a source file
src/GitHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/GitHandler.cpp.i
.PHONY : src/GitHandler.cpp.i

src/GitHandler.s: src/GitHandler.cpp.s
.PHONY : src/GitHandler.s

# target to generate assembly for a file
src/GitHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/GitHandler.cpp.s
.PHONY : src/GitHandler.cpp.s

src/GitHubAPI.o: src/GitHubAPI.cpp.o
.PHONY : src/GitHubAPI.o

# target to build an object file
src/GitHubAPI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/GitHubAPI.cpp.o
.PHONY : src/GitHubAPI.cpp.o

src/GitHubAPI.i: src/GitHubAPI.cpp.i
.PHONY : src/GitHubAPI.i

# target to preprocess a source file
src/GitHubAPI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/GitHubAPI.cpp.i
.PHONY : src/GitHubAPI.cpp.i

src/GitHubAPI.s: src/GitHubAPI.cpp.s
.PHONY : src/GitHubAPI.s

# target to generate assembly for a file
src/GitHubAPI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/GitHubAPI.cpp.s
.PHONY : src/GitHubAPI.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AIGitAgent.dir/build.make CMakeFiles/AIGitAgent.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AIGitAgent"
	@echo "... src/GitHandler.o"
	@echo "... src/GitHandler.i"
	@echo "... src/GitHandler.s"
	@echo "... src/GitHubAPI.o"
	@echo "... src/GitHubAPI.i"
	@echo "... src/GitHubAPI.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

